version: '3.8'
services:
  rbac-api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: rbac
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  homeassistant:
    image: homeassistant/home-assistant:stable
    volumes:
      - ./config:/config
    ports:
      - "8123:8123"
